[features]
seeds = false
skip-lint = false

[programs.localnet]
fantasy_league = "GVzcRC2a6iHReZbiED5RNJ3R1geCK7hn2gBiA3rEKtwN"

[programs.devnet]
fantasy_league = "GVzcRC2a6iHReZbiED5RNJ3R1geCK7hn2gBiA3rEKtwN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
