[features]
seeds = false
skip-lint = false

[programs.localnet]
fantasy_league = "HkZRTjyhTBERS5Q7WVQd2ruFscaB5ZAbLyt9USG6XAcb"

[programs.devnet]
fantasy_league = "HkZRTjyhTBERS5Q7WVQd2ruFscaB5ZAbLyt9USG6XAcb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
