const STOCK_NAMES: Record<string, string> = {
  AAPL: 'Apple Inc.',
  MSFT: 'Microsoft Corp.',
  GOOGL: 'Alphabet Inc.',
  AMZN: 'Amazon.com Inc.',
  NVDA: 'NVIDIA Corp.',
  META: 'Meta Platforms',
  'BRK.B': 'Berkshire Hathaway',
  LLY: 'Eli Lilly & Co.',
  TSM: 'Taiwan Semiconductor',
  V: 'Visa Inc.',
  UNH: 'UnitedHealth Group',
  JPM: 'JPMorgan Chase',
  WMT: 'Walmart Inc.',
  XOM: 'Exxon Mobil',
  JNJ: 'Johnson & Johnson',
  MA: 'Mastercard Inc.',
  PG: 'Procter & Gamble',
  AVGO: 'Broadcom Inc.',
  HD: 'Home Depot',
  CVX: 'Chevron Corp.',
  MRK: 'Merck & Co.',
  KO: 'Coca-Cola Co.',
  PEP: 'PepsiCo Inc.',
  COST: 'Costco Wholesale',
  ABBV: 'AbbVie Inc.',
  BAC: 'Bank of America',
  PFE: 'Pfizer Inc.',
  TMO: 'Thermo Fisher',
  CRM: 'Salesforce Inc.',
  ACN: 'Accenture plc',
  MCD: "McDonald's Corp.",
  CSCO: 'Cisco Systems',
  LIN: 'Linde plc',
  DHR: 'Danaher Corp.',
  ADBE: 'Adobe Inc.',
  VZ: 'Verizon Comm.',
  NFLX: 'Netflix Inc.',
  NKE: 'Nike Inc.',
  TXN: 'Texas Instruments',
  PM: 'Philip Morris Intl.',
  DIS: 'Walt Disney Co.',
  WFC: 'Wells Fargo',
  UPS: 'United Parcel Service',
  BMY: 'Bristol-Myers Squibb',
  RTX: 'RTX Corp.',
  ORCL: 'Oracle Corp.',
  QCOM: 'Qualcomm Inc.',
  HON: 'Honeywell Intl.',
  LOW: "Lowe's Companies",
  INTU: 'Intuit Inc.',
}

export function companyName(symbol: string): string {
  return STOCK_NAMES[symbol.toUpperCase()] ?? symbol
}

export default STOCK_NAMES
