const STOCK_NAMES: Record<string, string> = {
  MMM: '3M Co.',
  AOS: 'A.O. Smith',
  ABT: 'Abbott Laboratories',
  ABBV: 'AbbVie Inc.',
  ACN: 'Accenture plc',
  ADBE: 'Adobe Inc.',
  AMD: 'Advanced Micro Devices',
  AES: 'AES Corp.',
  AFL: 'Aflac Inc.',
  A: 'Agilent Technologies',
  APD: 'Air Products',
  ABNB: 'Airbnb Inc.',
  AKAM: 'Akamai Technologies',
  ALB: 'Albemarle Corp.',
  ARE: 'Alexandria Real Estate',
  ALGN: 'Align Technology',
  ALLE: 'Allegion plc',
  LNT: 'Alliant Energy',
  ALL: 'Allstate Corp.',
  GOOGL: 'Alphabet Inc. (A)',
  GOOG: 'Alphabet Inc. (C)',
  MO: 'Altria Group',
  AMZN: 'Amazon.com Inc.',
  AMCR: 'Amcor plc',
  AEE: 'Ameren Corp.',
  AEP: 'American Electric Power',
  AXP: 'American Express',
  AIG: 'American Intl. Group',
  AMT: 'American Tower',
  AWK: 'American Water Works',
  AMP: 'Ameriprise Financial',
  AME: 'Ametek Inc.',
  AMGN: 'Amgen Inc.',
  APH: 'Amphenol Corp.',
  ADI: 'Analog Devices',
  AON: 'Aon plc',
  APA: 'APA Corp.',
  APO: 'Apollo Global Mgmt.',
  AAPL: 'Apple Inc.',
  AMAT: 'Applied Materials',
  APP: 'AppLovin Corp.',
  APTV: 'Aptiv plc',
  ACGL: 'Arch Capital Group',
  ADM: 'Archer Daniels Midland',
  ARES: 'Ares Management',
  ANET: 'Arista Networks',
  AJG: 'Arthur J. Gallagher',
  AIZ: 'Assurant Inc.',
  T: 'AT&T Inc.',
  ATO: 'Atmos Energy',
  ADSK: 'Autodesk Inc.',
  ADP: 'Automatic Data Proc.',
  AZO: 'AutoZone Inc.',
  AVB: 'AvalonBay Communities',
  AVY: 'Avery Dennison',
  AXON: 'Axon Enterprise',
  BKR: 'Baker Hughes',
  BALL: 'Ball Corp.',
  BAC: 'Bank of America',
  BAX: 'Baxter Intl.',
  BDX: 'Becton Dickinson',
  'BRK.B': 'Berkshire Hathaway',
  BBY: 'Best Buy Co.',
  BIO: 'Bio-Rad Labs',
  TECH: 'Bio-Techne Corp.',
  BIIB: 'Biogen Inc.',
  BK: 'BNY Mellon',
  BX: 'Blackstone Inc.',
  BA: 'Boeing Co.',
  BKNG: 'Booking Holdings',
  BWA: 'BorgWarner Inc.',
  BSX: 'Boston Scientific',
  BMY: 'Bristol-Myers Squibb',
  AVGO: 'Broadcom Inc.',
  BR: 'Broadridge Financial',
  BRO: 'Brown & Brown',
  'BF.B': 'Brown-Forman (B)',
  BLDR: 'Builders FirstSource',
  BG: 'Bunge Global',
  BXP: 'BXP Inc.',
  CDNS: 'Cadence Design Sys.',
  CZR: 'Caesars Entertainment',
  CPT: 'Camden Property Trust',
  CPB: "Campbell's Co.",
  COF: 'Capital One Financial',
  CAH: 'Cardinal Health',
  KMX: 'CarMax Inc.',
  CCL: 'Carnival Corp.',
  CARR: 'Carrier Global',
  CVNA: 'Carvana Co.',
  CAT: 'Caterpillar Inc.',
  CBOE: 'Cboe Global Markets',
  CBRE: 'CBRE Group',
  CDW: 'CDW Corp.',
  CE: 'Celanese Corp.',
  COR: 'Cencora Inc.',
  CNC: 'Centene Corp.',
  CNP: 'CenterPoint Energy',
  CF: 'CF Industries',
  CRL: 'Charles River Labs',
  SCHW: 'Charles Schwab',
  CHTR: 'Charter Communications',
  CVX: 'Chevron Corp.',
  CMG: 'Chipotle Mexican Grill',
  CB: 'Chubb Ltd.',
  CHD: 'Church & Dwight',
  CIEN: 'Ciena Corp.',
  CI: 'Cigna Group',
  CINF: 'Cincinnati Financial',
  CTAS: 'Cintas Corp.',
  CSCO: 'Cisco Systems',
  C: 'Citigroup Inc.',
  CFG: 'Citizens Financial',
  CLX: 'Clorox Co.',
  CME: 'CME Group',
  CMS: 'CMS Energy',
  KO: 'Coca-Cola Co.',
  CTSH: 'Cognizant Tech.',
  COHR: 'Coherent Corp.',
  COIN: 'Coinbase Global',
  CL: 'Colgate-Palmolive',
  CMCSA: 'Comcast Corp.',
  CAG: 'Conagra Brands',
  COP: 'ConocoPhillips',
  ED: 'Consolidated Edison',
  STZ: 'Constellation Brands',
  CEG: 'Constellation Energy',
  COO: 'Cooper Companies',
  CPRT: 'Copart Inc.',
  GLW: 'Corning Inc.',
  CPAY: 'Corpay Inc.',
  CTVA: 'Corteva Inc.',
  CSGP: 'CoStar Group',
  COST: 'Costco Wholesale',
  CTRA: 'Coterra Energy',
  CRWD: 'CrowdStrike Holdings',
  CCI: 'Crown Castle',
  CSX: 'CSX Corp.',
  CMI: 'Cummins Inc.',
  CVS: 'CVS Health',
  DHR: 'Danaher Corp.',
  DRI: "Darden Restaurants",
  DVA: 'DaVita Inc.',
  DAY: 'Dayforce Inc.',
  DECK: 'Deckers Outdoor',
  DE: 'Deere & Co.',
  DELL: 'Dell Technologies',
  DAL: 'Delta Air Lines',
  DVN: 'Devon Energy',
  DXCM: 'DexCom Inc.',
  FANG: 'Diamondback Energy',
  DLR: 'Digital Realty',
  DFS: 'Discover Financial',
  DG: 'Dollar General',
  DLTR: 'Dollar Tree',
  D: 'Dominion Energy',
  DPZ: "Domino's Pizza",
  DOV: 'Dover Corp.',
  DOW: 'Dow Inc.',
  DHI: 'D.R. Horton',
  DTE: 'DTE Energy',
  DUK: 'Duke Energy',
  DD: 'DuPont de Nemours',
  EMN: 'Eastman Chemical',
  ETN: 'Eaton Corp.',
  EBAY: 'eBay Inc.',
  ECL: 'Ecolab Inc.',
  EIX: 'Edison Intl.',
  EW: 'Edwards Lifesciences',
  EA: 'Electronic Arts',
  ELV: 'Elevance Health',
  EMR: 'Emerson Electric',
  ENPH: 'Enphase Energy',
  ETR: 'Entergy Corp.',
  EOG: 'EOG Resources',
  EPAM: 'EPAM Systems',
  EQT: 'EQT Corp.',
  EFX: 'Equifax Inc.',
  EQIX: 'Equinix Inc.',
  EQR: 'Equity Residential',
  ERIE: 'Erie Indemnity',
  ESS: 'Essex Property Trust',
  EL: 'Estée Lauder',
  ETSY: 'Etsy Inc.',
  EG: 'Everest Group',
  EVRG: 'Evergy Inc.',
  ES: 'Eversource Energy',
  EXC: 'Exelon Corp.',
  EXPE: 'Expedia Group',
  EXPD: 'Expeditors Intl.',
  EXR: 'Extra Space Storage',
  XOM: 'Exxon Mobil',
  FFIV: 'F5 Inc.',
  FDS: 'FactSet Research',
  FICO: 'Fair Isaac Corp.',
  FAST: 'Fastenal Co.',
  FRT: 'Federal Realty',
  FDX: 'FedEx Corp.',
  FITB: 'Fifth Third Bancorp',
  FSLR: 'First Solar',
  FE: 'FirstEnergy Corp.',
  FI: 'Fiserv Inc.',
  FIS: 'Fidelity Natl. Info.',
  FMC: 'FMC Corp.',
  F: 'Ford Motor Co.',
  FTNT: 'Fortinet Inc.',
  FTV: 'Fortive Corp.',
  FOXA: 'Fox Corp. (A)',
  FOX: 'Fox Corp. (B)',
  BEN: 'Franklin Resources',
  FCX: 'Freeport-McMoRan',
  GRMN: 'Garmin Ltd.',
  IT: 'Gartner Inc.',
  GE: 'GE Aerospace',
  GEHC: 'GE HealthCare',
  GEV: 'GE Vernova',
  GEN: 'Gen Digital',
  GNRC: 'Generac Holdings',
  GD: 'General Dynamics',
  GIS: 'General Mills',
  GM: 'General Motors',
  GPC: 'Genuine Parts',
  GILD: 'Gilead Sciences',
  GPN: 'Global Payments',
  GL: 'Globe Life',
  GDDY: 'GoDaddy Inc.',
  GS: 'Goldman Sachs',
  HAL: 'Halliburton Co.',
  HIG: 'Hartford Financial',
  HAS: 'Hasbro Inc.',
  HCA: 'HCA Healthcare',
  PEAK: 'Healthpeak Properties',
  HSIC: 'Henry Schein',
  HSY: 'Hershey Co.',
  HES: 'Hess Corp.',
  HPE: 'Hewlett Packard Ent.',
  HLT: 'Hilton Worldwide',
  HOLX: 'Hologic Inc.',
  HD: 'Home Depot',
  HON: 'Honeywell Intl.',
  HRL: 'Hormel Foods',
  HST: 'Host Hotels',
  HWM: 'Howmet Aerospace',
  HPQ: 'HP Inc.',
  HUBB: 'Hubbell Inc.',
  HUM: 'Humana Inc.',
  HBAN: 'Huntington Bancshares',
  HII: 'HII (Huntington Ingalls)',
  IBM: 'IBM',
  IEX: 'IDEX Corp.',
  IDXX: 'Idexx Laboratories',
  ITW: 'Illinois Tool Works',
  INCY: 'Incyte Corp.',
  IR: 'Ingersoll Rand',
  PODD: 'Insulet Corp.',
  INTC: 'Intel Corp.',
  ICE: 'Intercontinental Exch.',
  IFF: 'Intl. Flavors & Frag.',
  IP: 'International Paper',
  IPG: 'Interpublic Group',
  INTU: 'Intuit Inc.',
  ISRG: 'Intuitive Surgical',
  IVZ: 'Invesco Ltd.',
  INVH: 'Invitation Homes',
  IQV: 'IQVIA Holdings',
  IRM: 'Iron Mountain',
  JBHT: 'J.B. Hunt Transport',
  JBL: 'Jabil Inc.',
  JKHY: 'Jack Henry & Assoc.',
  J: 'Jacobs Solutions',
  JNJ: 'Johnson & Johnson',
  JCI: 'Johnson Controls',
  JPM: 'JPMorgan Chase',
  JNPR: 'Juniper Networks',
  K: 'Kellanova',
  KVUE: 'Kenvue Inc.',
  KDP: 'Keurig Dr Pepper',
  KEY: 'KeyCorp',
  KEYS: 'Keysight Technologies',
  KMB: 'Kimberly-Clark',
  KIM: 'Kimco Realty',
  KMI: 'Kinder Morgan',
  KKR: 'KKR & Co.',
  KLAC: 'KLA Corp.',
  KHC: 'Kraft Heinz',
  KR: 'Kroger Co.',
  LHX: 'L3Harris Technologies',
  LH: 'Labcorp Holdings',
  LRCX: 'Lam Research',
  LW: 'Lamb Weston',
  LVS: 'Las Vegas Sands',
  LDOS: 'Leidos Holdings',
  LEN: 'Lennar Corp.',
  LII: 'Lennox Intl.',
  LIN: 'Linde plc',
  LYV: 'Live Nation Ent.',
  LKQ: 'LKQ Corp.',
  LMT: 'Lockheed Martin',
  L: 'Loews Corp.',
  LOW: "Lowe's Companies",
  LULU: 'Lululemon Athletica',
  LYB: 'LyondellBasell',
  MTB: 'M&T Bank',
  MRO: 'Marathon Oil',
  MPC: 'Marathon Petroleum',
  MKTX: 'MarketAxess Holdings',
  MAR: 'Marriott Intl.',
  MMC: 'Marsh & McLennan',
  MLM: 'Martin Marietta',
  MAS: 'Masco Corp.',
  MA: 'Mastercard Inc.',
  MTCH: 'Match Group',
  MKC: 'McCormick & Co.',
  MCD: "McDonald's Corp.",
  MCK: 'McKesson Corp.',
  MDT: 'Medtronic plc',
  MRK: 'Merck & Co.',
  META: 'Meta Platforms',
  MCHP: 'Microchip Technology',
  MU: 'Micron Technology',
  MSFT: 'Microsoft Corp.',
  MAA: 'Mid-America Apartment',
  MRNA: 'Moderna Inc.',
  MHK: 'Mohawk Industries',
  MOH: 'Molina Healthcare',
  TAP: 'Molson Coors',
  MDLZ: 'Mondelez Intl.',
  MPWR: 'Monolithic Power Sys.',
  MNST: 'Monster Beverage',
  MCO: "Moody's Corp.",
  MS: 'Morgan Stanley',
  MOS: 'Mosaic Co.',
  MSI: 'Motorola Solutions',
  MSCI: 'MSCI Inc.',
  NDAQ: 'Nasdaq Inc.',
  NTAP: 'NetApp Inc.',
  NFLX: 'Netflix Inc.',
  NEM: 'Newmont Corp.',
  NWSA: 'News Corp. (A)',
  NWS: 'News Corp. (B)',
  NEE: 'NextEra Energy',
  NKE: 'Nike Inc.',
  NI: 'NiSource Inc.',
  NDSN: 'Nordson Corp.',
  NSC: 'Norfolk Southern',
  NTRS: 'Northern Trust',
  NOC: 'Northrop Grumman',
  NCLH: 'Norwegian Cruise Line',
  NRG: 'NRG Energy',
  NUE: 'Nucor Corp.',
  NVDA: 'NVIDIA Corp.',
  NVR: 'NVR Inc.',
  NXPI: 'NXP Semiconductors',
  ORLY: "O'Reilly Automotive",
  OXY: 'Occidental Petroleum',
  ODFL: 'Old Dominion Freight',
  OMC: 'Omnicom Group',
  ON: 'ON Semiconductor',
  OKE: 'ONEOK Inc.',
  ORCL: 'Oracle Corp.',
  OTIS: 'Otis Worldwide',
  PCAR: 'PACCAR Inc.',
  PKG: 'Packaging Corp.',
  PANW: 'Palo Alto Networks',
  PH: 'Parker Hannifin',
  PAYX: 'Paychex Inc.',
  PAYC: 'Paycom Software',
  PYPL: 'PayPal Holdings',
  PNR: 'Pentair plc',
  PEP: 'PepsiCo Inc.',
  PFE: 'Pfizer Inc.',
  PCG: 'PG&E Corp.',
  PM: 'Philip Morris Intl.',
  PSX: 'Phillips 66',
  PNW: 'Pinnacle West Capital',
  PNC: 'PNC Financial',
  POOL: 'Pool Corp.',
  PPG: 'PPG Industries',
  PPL: 'PPL Corp.',
  PFG: 'Principal Financial',
  PG: 'Procter & Gamble',
  PGR: 'Progressive Corp.',
  PLD: 'Prologis Inc.',
  PRU: 'Prudential Financial',
  PEG: 'Public Svc. Enterprise',
  PTC: 'PTC Inc.',
  PSA: 'Public Storage',
  PHM: 'PulteGroup Inc.',
  QRVO: 'Qorvo Inc.',
  PWR: 'Quanta Services',
  QCOM: 'Qualcomm Inc.',
  DGX: 'Quest Diagnostics',
  RL: 'Ralph Lauren',
  RJF: 'Raymond James',
  RTX: 'RTX Corp.',
  O: 'Realty Income',
  REG: 'Regency Centers',
  REGN: 'Regeneron Pharma.',
  RF: 'Regions Financial',
  RSG: 'Republic Services',
  RMD: 'ResMed Inc.',
  RVTY: 'Revvity Inc.',
  RHI: 'Robert Half Intl.',
  ROK: 'Rockwell Automation',
  ROL: 'Rollins Inc.',
  ROP: 'Roper Technologies',
  ROST: 'Ross Stores',
  RCL: 'Royal Caribbean',
  SPGI: 'S&P Global',
  CRM: 'Salesforce Inc.',
  SBAC: 'SBA Communications',
  SLB: 'Schlumberger',
  STX: 'Seagate Technology',
  SRE: 'Sempra',
  NOW: 'ServiceNow Inc.',
  SHW: 'Sherwin-Williams',
  SPG: 'Simon Property Group',
  SWKS: 'Skyworks Solutions',
  SJM: 'J.M. Smucker',
  SW: 'Smurfit Westrock',
  SNA: 'Snap-on Inc.',
  SOLV: 'Solventum Corp.',
  SO: 'Southern Co.',
  LUV: 'Southwest Airlines',
  SWK: 'Stanley Black & Decker',
  SBUX: 'Starbucks Corp.',
  STT: 'State Street Corp.',
  STLD: 'Steel Dynamics',
  STE: 'Steris plc',
  SYK: 'Stryker Corp.',
  SMCI: 'Super Micro Computer',
  SYF: 'Synchrony Financial',
  SNPS: 'Synopsys Inc.',
  SYY: 'Sysco Corp.',
  TMUS: 'T-Mobile US',
  TROW: 'T. Rowe Price',
  TTWO: 'Take-Two Interactive',
  TPR: 'Tapestry Inc.',
  TRGP: 'Targa Resources',
  TGT: 'Target Corp.',
  TEL: 'TE Connectivity',
  TDY: 'Teledyne Technologies',
  TFX: 'Teleflex Inc.',
  TER: 'Teradyne Inc.',
  TSLA: 'Tesla Inc.',
  TXN: 'Texas Instruments',
  TXT: 'Textron Inc.',
  TMO: 'Thermo Fisher',
  TJX: 'TJX Companies',
  TSCO: 'Tractor Supply',
  TT: 'Trane Technologies',
  TDG: 'TransDigm Group',
  TRV: 'Travelers Companies',
  TRMB: 'Trimble Inc.',
  TFC: 'Truist Financial',
  TYL: 'Tyler Technologies',
  TSN: 'Tyson Foods',
  USB: 'U.S. Bancorp',
  UBER: 'Uber Technologies',
  UDR: 'UDR Inc.',
  ULTA: 'Ulta Beauty',
  UNP: 'Union Pacific',
  UAL: 'United Airlines',
  UPS: 'United Parcel Service',
  URI: 'United Rentals',
  UNH: 'UnitedHealth Group',
  UHS: 'Universal Health Svc.',
  VLO: 'Valero Energy',
  VTR: 'Ventas Inc.',
  VLTO: 'Veralto Corp.',
  VRSN: 'VeriSign Inc.',
  VRSK: 'Verisk Analytics',
  VZ: 'Verizon Comm.',
  VRTX: 'Vertex Pharma.',
  VIAV: 'Viavi Solutions',
  VFC: 'VF Corp.',
  VICI: 'Vici Properties',
  V: 'Visa Inc.',
  VST: 'Vistra Corp.',
  VMC: 'Vulcan Materials',
  WRB: 'W.R. Berkley',
  GWW: 'W.W. Grainger',
  WAB: 'Westinghouse Air Brake',
  WBA: 'Walgreens Boots',
  WMT: 'Walmart Inc.',
  DIS: 'Walt Disney Co.',
  WBD: 'Warner Bros. Discovery',
  WM: 'Waste Management',
  WAT: 'Waters Corp.',
  WEC: 'WEC Energy Group',
  WFC: 'Wells Fargo',
  WELL: 'Welltower Inc.',
  WST: 'West Pharma. Svc.',
  WDC: 'Western Digital',
  WRK: 'WestRock Co.',
  WY: 'Weyerhaeuser Co.',
  WMB: 'Williams Companies',
  WTW: 'Willis Towers Watson',
  WYNN: 'Wynn Resorts',
  XEL: 'Xcel Energy',
  XYL: 'Xylem Inc.',
  YUM: 'Yum! Brands',
  ZBRA: 'Zebra Technologies',
  ZBH: 'Zimmer Biomet',
  ZTS: 'Zoetis Inc.',
}

export function companyName(symbol: string): string {
  return STOCK_NAMES[symbol.toUpperCase()] ?? symbol
}

export default STOCK_NAMES
